### ISSUE TITLE
5 thor power not working

### ISSUE THREAD

**Issue by ghost** [Sky4ce09/wco#2]
the schematic 5thoreactor is not working
and why there is hhh = hhh in the start of the code ?
![image](https://user-images.githubusercontent.com/87120277/128647708-a6ad3f96-58ea-43c0-9735-43a13dfb8609.png)

**Comment by Sky4ce09** [comment]
the "hhh" is there because im not using text editors at the moment -> no selfjumps

**Comment by Sky4ce09** [comment]
about the schematic not working:
-did you build a resource outpost link and link a storage block to it?
-if so, then in what way does the schematic misbehave?

**Comment by ghost** [comment]
> about the schematic not working:
> -did you build a resource outpost link and link a storage block to it?

yes
> -if so, then in what way does the schematic misbehave?

it will take from the old storage even if there is no thor 
and i have try to build new 'resource outpost link' and still try to take from the old one
(sorry for reply late)

**Comment by Sky4ce09** [comment]
> > about the schematic not working:
> > -did you build a resource outpost link and link a storage block to it?
> 
> yes
> 
> > -if so, then in what way does the schematic misbehave?
> 
> it will take from the old storage even if there is no thor
> and i have try to build new 'resource outpost link' and still try to take from the old one
> (sorry for reply late)

i see
this is because the processors don't automatically try to find new outpost links
(in theory i can get them to periodically send a flare to check if a storage block is available) actually, checking the block variable for null is an infinitely better solution
